name: Helm Chart Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  lint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest' # You can change this to the version you're using
    
    - name: Lint Helm Charts
      run: |
        helm lint helm-chart/