name: Package and Push Helm Charts

on:
  workflow_run:
    workflows: ["Helm Chart Lint"]
    types:
      - completed
  workflow_dispatch:

jobs:
  package_and_push:
    name: Package and Push Helm Charts
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Helm Chart Lint'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.0.0' # You can change this to the version you're using
    
    - name: Package Helm Charts
      run: |
        helm package helm-chart/

    - name: Auth with Cloud
      uses: google-github-actions/auth@v2
      with: 
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        token_format: access_token

    - name: Authenticate with Artifact Registry
      run: gcloud auth configure-docker \us-central1-docker.pkg.dev --quiet

    - name: Push Helm Charts to Artifact Registry
      run: |
        helm push ./packaged-charts/*.tgz oci://us-central1-docker.pkg.dev/genuine-plate-417822/my-artifact-repo