name: Package and Push Helm Charts

on:
  workflow_run:
    workflows: ["Helm Chart Lint"]
    types:
      - completed
  workflow_dispatch:

env:
    PROJECT_ID: genuine-plate-417822
    REGISTRY_LOCATION: us-central1
    REPOSITORY: my-artifact-repo

jobs:
  package_and_push:
    name: Package and Push Helm Charts
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Helm Chart Lint'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.0.0' # You can change this to the version you're using
    
    - name: Package Helm Charts
      run: |
        helm package helm-chart/ -d ./packaged-charts
      working-directory: ${{ github.workspace }}

    - name: Auth with Cloud
      uses: google-github-actions/auth@v2
      with: 
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: access_token

    - name: Helm Login
      run: 
        export HELM_EXPERIMENTAL_OCI=1
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken \
        --password-stdin https://us-central1-docker.pkg.dev

    - name: Push Helm Charts to Artifact Registry
      run: |
        helm push ./packaged-charts/*.tgz "oci://us-central1-docker.pkg.dev/genuine-plate-417822/my-artifact-repo"